### PR TITLE
sensiolabs_security_checker and puppetlint

### LINKED ISSUE #176: use sensiolabs_security_checker and puppetlint also from scrutinizer

### PR DESCRIPTION
**Pull request by benbieler**
Resolves #176

### CODE REVIEW

**Comment by Ma27** [comment]
:+1:

**Comment by Ma27** [comment]
I assume you forgot to pull master again after some of my changes yesterday :)
After doing this, you should be able to easily merge this.

**Comment by benbieler** [comment]
Jap, sorry about that

**Comment by Ma27** [comment]
retriggered build

**Comment by Ma27** [comment]
our tests behave currently quite odd. I've created a ticket to investigate, but currently the only solution is retriggering the build :/

**Pull request merged**
