### PR TITLE
Remove ORM subnamespace from Doctrine namespace

### LINKED ISSUE #182: remove ORM subnamespace from Doctrine namespace
all classes inside AppBundle\Doctrine\ORM should be moved to AppBundle\Doctrine since we don't support any other doctrine implementations, so we don't need to create sub-dirs.

Notice: the DataFixtures/ORM classes should **not** be moved since the DoctrineFixturesBundle lookups all fixture classes in that directory.

### PR DESCRIPTION
**Pull request by benbieler**
Resolves #182

### CODE REVIEW

**Comment by Ma27** [comment]
the files should be moved from dir "AppBundle/Doctrine/ORM" to "AppBundle/Doctrine". Same for the tests (AppBundle\Tests\Doctrine\ORM -> AppBundle\Tests\Doctrine)

**Comment by benbieler** [comment]
Sorry about that. This should be fixed in the latest comit...

**Comment by Ma27** [comment]
ok :+1:

2016-01-22 20:46 GMT+01:00 Ben Bieler notifications@github.com:

**Comment by Ma27** [comment]
@benbieler our travis-ci behaves currently quite odd. I've created some bugfixes, but I currently have no idea why the builds sometimes break. I've retriggered the build and let's hop eit works now.

After that please change your commit message to the following schema:

```
Refactor #182 remove unnecessary "ORM" sub-namespace of doctrine related files
```

and then hit the green button ;)

**Comment by Ma27** [comment]
...and restarting it again, sry...

**Comment by Ma27** [comment]
quite interesting, the push build fails (the pr quite rarely). NPM modules are missing or the authentication fails...

**Comment by Ma27** [comment]
test passing finally, squash and merge ;)

**Comment by Ma27** [comment]
thanks for your contribution @benbieler

**Pull request merged**
