### PR TITLE
roave/security-advisories

### LINKED ISSUE #202: use roave/security-advisories
to avoid any security issues, this package might be helpful

### PR DESCRIPTION
**Pull request by benbieler**
Resolves #202

### CODE REVIEW

**Comment by Ma27** [comment]
could you please run a "composer update" in order to sync the changes into the lock file?

**Comment by benbieler** [comment]
composer update & squashed

**Comment by Ma27** [comment]
thanks!

**Comment by Ma27** [comment]
please squash with `git rebase -i HEAD~2 --preserve-merges`

**Comment by Ma27** [comment]
rebasing and merging now...

**Pull request merged**
